services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: BBD_CRM
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: ./api_node
    image: nodeapp:v1
    environment:
      DB_HOST: mysqldb
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: BBD_CRM
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 10
      SERVER_PORT: 5000
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - mysqldb
    networks:
      - internalnet


  reactclient:
    build: ./client
    container_name: reactappcontainer
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    
  reactclient2:
    build: ./panel
    container_name: reactappcontainer2
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    
networks:
  internalnet:
    driver: bridge
